version: '3'

services:
  database: 
    build: ./redis
    restart: always
  
  elasticsearch: 
    image: elasticsearch
    restart: always
    healthcheck:
      test: curl --silent --fail localhost:9200/_cluster/health || exit 1